<?php

namespace App\Controller\Api;


abstract class Structure
{
    const
        ORDER_ID = 'order_id',
        DATE_ADD = 'date_add',
        CHANGE_DATE = 'change_date',
        DELIVERY_DATE = 'delivery_date',
        DELIVERY_TIME1 = 'delivery_time1',
        DELIVERY_TIME2 = 'delivery_time2',
        STATUS = 'status',
        TYPE = 'type',
        PVZ_ID = 'pvz_id',
        POST_INDEX = 'post_index',
        POST_ADDR = 'post_addr',
        REG_CITY = 'reg_city',
        REG_FULLADDR = 'reg_fulladdr',
        CITY = 'city',
        MO_PUNKT_ID = 'mo_punkt_id',
        MO_MKAD = 'mo_mkad',
        ZONE_ID = 'zone_id',
        STREET = 'street',
        BUILDING = 'building',
        CORPUS = 'corpus',
        OFFICE = 'office',
        DOMOFON = 'domofon',
        FLOOR = 'floor',
        TARGET_NAME = 'target_name',
        RECIEPIENT_NAME = 'reciepient_name',
        DOC_DESCRIPTION = 'doc_description',
        CLIENT_ID = 'client_id',
        COURIER_ID = 'courier_id',
        COUR_CID = 'cour_cid',
        TARGET_CONTACTS = 'target_contacts',
        TARGET_NOTES = 'target_notes',
        ADM_NOTES = 'adm_notes',
        LONGITUDE = 'longitude',
        PRICE_COURIER = 'price_courier',
        PRICE_GOODS = 'price_goods',
        PRICE_CLIENT = 'price_client',
        OS = 'os',
        DIMENSION_SIDE1 = 'dimension_side1',
        DIMENSION_SIDE2 = 'dimension_side2',
        DIMENSION_SIDE3 = 'dimension_side3',
        PD_TAR = 'pd_tar',
        PD_KO = 'pd_ko',
        PD_DOP = 'pd_dop',
        PD_DOP_STRAH = 'pd_dop_strah',
        PD_DOP_COMPL = 'pd_dop_compl',
        PD_EQ = 'pd_eq',
        PD_CALL = 'pd_call',
        PD_SMS = 'pd_sms',
        PD_LABEL = 'pd_label',
        PD_DOCS = 'pd_docs',
        PD_DOCS_RETURN = 'pd_docs_return',
        PD_CHANGE = 'pd_change',
        PD_DOP_PACK = 'pd_dop_pack',
        PD_DOP_VOZVRAT = 'pd_dop_vozvrat',
        PRICE_DELIVERY = 'price_delivery',
        SUM2P = 'sum2p',
        PRICE_CLIENT_DELIVERY = 'price_client_delivery',
        NDS_PRICE_CLIENT = 'nds_price_client',
        IS_PACKED = 'is_packed',
        NP = 'np',
        SMS = 'sms',
        IS_COMPLECT = 'is_complect',
        LATITUDE = 'latitude',
        CARD = 'card',
        CARD_TYPE = 'card_type',
        AGENT_ID = 'agent_id',
        AGENT_COST = 'agent_cost',
        AGENT_ACT = 'agent_act',
        AGENT_VACT = 'agent_vact',
        MANAGER_ID = 'manager_id',
        ISOH = 'isoh',
        OTKAZMARK = 'otkazmark',
        P_REASON = 'p_reason',
        ORDERCALL = 'ordercall',
        INNER_N = 'inner_n',
        BRAND = 'brand',
        SHK = 'shk',
        ORDER_WEIGHT = 'order_weight',
        CHWEIGHTFLAG = 'chweightflag',
        UPDATE_DATE_FLAG = 'update_date_flag',
        BILL_ID = 'bill_id',
        AKT_ID = 'akt_id',
        REG_BILL_ID = 'reg_bill_id',
        PARTNER_ACT = 'partner_act',
        OPEN_OPTION = 'open_option',
        CALL_OPTION = 'call_option',
        LABEL_OPTION = 'label_option',
        PLACES_COUNT = 'places_count',
        DOCS_OPTION = 'docs_option',
        DOCS_RETURN_OPTION = 'docs_return_option',
        PARTIAL_OPTION = 'partial_option',
        DRESS_FITTING_OPTION = 'dress_fitting_option',
        LIFTING_OPTION = 'lifting_option',
        CARGO_LIFT = 'cargo_lift',
        CHANGE_OPTION = 'change_option',
        CHANGE_TEXT = 'change_text',
        CHANGE_OS = 'change_os',
        CHANGE_WEIGHT = 'change_weight',
        ORDERPLACE = 'orderPlace',
        PIMP_SEND = 'pimp_send',
        PIMPAY_STATUS = 'pimpay_status';

    public static $fields = [
        \Orders::class => [
            self::ORDER_ID,
            self::DATE_ADD,
            self::CHANGE_DATE,
            self::DELIVERY_DATE,
            self::DELIVERY_TIME1,
            self::DELIVERY_TIME2,
            self::STATUS,
            self::TYPE,
            self::TARGET_NAME,
            self::CLIENT_ID,
            self::COURIER_ID,
            self::COUR_CID,
            self::TARGET_CONTACTS,
            self::TARGET_NOTES,
            self::ADM_NOTES,
            self::NDS_PRICE_CLIENT,
            self::IS_PACKED,
            self::NP,
            self::SMS,
            self::IS_COMPLECT,
            self::CARD,
            self::CARD_TYPE,
            self::AGENT_ID,
            self::AGENT_ACT,
            self::AGENT_VACT,
            self::MANAGER_ID,
            self::ISOH,
            self::OTKAZMARK,
            self::P_REASON,
            self::ORDERCALL,
            self::INNER_N,
            self::BRAND,
            self::SHK,
            self::ORDER_WEIGHT,
            self::CHWEIGHTFLAG,
            self::UPDATE_DATE_FLAG,
            self::BILL_ID,
            self::AKT_ID,
            self::REG_BILL_ID,
            self::PARTNER_ACT,
            self::OPEN_OPTION,
            self::CALL_OPTION,
            self::LABEL_OPTION,
            self::PLACES_COUNT,
            self::DOCS_OPTION,
            self::DOCS_RETURN_OPTION,
            self::PARTIAL_OPTION,
            self::DRESS_FITTING_OPTION,
            self::LIFTING_OPTION,
            self::CARGO_LIFT,
            self::CHANGE_OPTION,
            self::CHANGE_TEXT,
            self::ORDERPLACE,
            self::PIMP_SEND,
            self::PIMPAY_STATUS
        ],
        \Address::class => [
            self::PVZ_ID,
            self::POST_INDEX,
            self::POST_ADDR,
            self::REG_CITY,
            self::REG_FULLADDR,
            self::CITY,
            self::MO_PUNKT_ID,
            self::MO_MKAD,
            self::ZONE_ID,
            self::STREET,
            self::BUILDING,
            self::CORPUS,
            self::OFFICE,
            self::DOMOFON,
            self::FLOOR,
            self::LONGITUDE,
            self::LATITUDE
        ],
        \OrdersBills::class => [
            self::PRICE_COURIER,
            self::PRICE_GOODS,
            self::PRICE_CLIENT,
            self::OS,
            self::DIMENSION_SIDE1,
            self::DIMENSION_SIDE2,
            self::DIMENSION_SIDE3,
            self::PD_TAR,
            self::PD_KO,
            self::PD_DOP,
            self::PD_DOP_STRAH,
            self::PD_DOP_COMPL,
            self::PD_EQ,
            self::PD_CALL,
            self::PD_SMS,
            self::PD_LABEL,
            self::PD_DOCS,
            self::PD_DOCS_RETURN,
            self::PD_CHANGE,
            self::PD_DOP_PACK,
            self::PD_DOP_VOZVRAT,
            self::PRICE_DELIVERY,
            self::SUM2P,
            self::PRICE_CLIENT_DELIVERY,
            self::AGENT_COST,
            self::CHANGE_OS,
            self::CHANGE_WEIGHT
        ],
        \OrdersSettings::class => [
            self::RECIEPIENT_NAME,
            self::DOC_DESCRIPTION
        ]
    ];
}